apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  selector:
    name: database
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
